services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Faker\Generator:
        factory: 'Faker\Factory::create'
        arguments: ["%locale%"]
        public: true

    BusinessFinder\AppBundle\:
        resource: '../../src/BusinessFinder/AppBundle/*'
        exclude: '../../src/BusinessFinder/AppBundle/{Entity,Repository,Menu}'

    BusinessFinder\AppBundle\Controller\:
        resource: '../../src/BusinessFinder/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']